import "./globals.css";
import  {Inter} from "next/font/google";
import {ThemeProvider} from "next-themes";
import Header from "@/components/Header";
import  {ClerkProvider} from "@clerk/nextjs";
import {neobrutalism, shadesOfPurple} from '@clerk/themes'


const inter = Inter({subsets:['latin']})

export const metadata = {
  title: "Learning project management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider
          appearance={{
              baseTheme:  shadesOfPurple
          }}
      >
          <html lang="en">
          <body
              className={`${inter.className}`}
          >
          <ThemeProvider attribute="class" defaultTheme='dark'>
              <Header/>
              <main className='min-h-screen'> {children}</main>
              <footer className='bg-gray-900 py-12 text-center'>
                  <div className='container text-gray-200 mx-auto px-4'>
                      <p>
                          Made by Trilochanprasad
                      </p>
                  </div>
              </footer>
          </ThemeProvider>
          </body>
          </html>
      </ClerkProvider>

  );
}
